apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-service-config
data:
  SPRING_PROFILES_ACTIVE: "cloud,logging"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://smym-db-server.postgres.database.azure.com:5432/smym"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak.scottmakesyoumove.com/realms/smym-dev"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak.scottmakesyoumove.com/realms/smym-dev/protocol/openid-connect/certs"
  SPRING_AI_VECTORSTORE_COSMOSDB_ENDPOINT: "https://smym-cosmos.documents.azure.com:443/"
  SPRING_AI_VECTORSTORE_COSMOSDB_INITIALIZE_SCHEMA: "false"
  SPRING_AI_VECTOR_STORE_COSMOSDB_DATABASE_NAME: "rag-knowledge-base"
  SPRING_AI_OPENAI_OPTIONS_MODEL: "gpt-3.5-turbo"
  SPRING_AI_OPENAI_EMBEDDING_OPTION_MODEL: "text-embedding-3-small"
  CHAT_CLIENT_ADVISORS_CHAT_MEMORY_ENABLED: "true"
  CHAT_CLIENT_ADVISORS_CHAT_MEMORY_MAX_MESSAGE: "20"
  CHAT_CLIENT_ADVISORS_LOGGING_ENABLED: "true"
  CHAT_CLIENT_ADVISORS_MASKING_ENABLED: "false"
  CHAT_CLIENT_ADVISORS_CHUNKS_ENABLED: "true"
  CHAT_CLIENT_ADVISORS_CHUNKS_SIMILARITYTHRESHOLD: "0.2"
  CHAT_CLIENT_ADVISORS_CHUNKS_TOPK: "3"
  CHAT_CLIENT_ADVISORS_FILES_ENABLED: "true"
  CHAT_CLIENT_ADVISORS_FILES_SIMILARITYTHRESHOLD: "0.0"
  CHAT_CLIENT_ADVISORS_FILES_TOPK: "20"
  GOOGLE_DRIVE_ROOT_FOLDER_ID: "1QcXQwIvODNozhCJW78Sp30QsY_Xfhabp"
  MICROSOFT_ENTRA_ID_CLIENT_ID: "b6471db2-0004-46bf-a3e1-143a709e167d"
  MICROSOFT_ENTRA_ID_TENANT_ID: "758c9aae-38da-48e7-9f09-943cae42886b"
  JWT_AUTH_CONVERTER_RESOURCE_ID: "smym-client"
  JWT_AUTH_CONVERTER_PRINICIPAL_ATTRIBUTE: "principal_username"
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak.scottmakesyoumove.com"
  KEYCLOAK_REALM_MASTER: "master"
  KEYCLOAK_REALM_SMYM: "smym-dev"
  KEYCLOAK_CLIENT_ADMIN: "admin-cli"
  KEYCLOAK_CLIENT_SMYM: "smym-client"
  NOTIFICATION_USER_ID: "4058614e-57f2-4e46-8427-eb103a435a13"
  NOTIFICATION_USER_EMAIL: "scott.everduim@outlook.com"
  NOTIFICATION_USER_NAME: "Scott Everduim"
  FRONTEND_URL: "http://scottmakesyoumove.com"
  APP_SECURITY_ENABLED: "true"
  SPRING_FLYWAY_ENABLED: "false"
