apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  GOOGLE_DRIVE_ROOT_FOLDER_ID: "1QcXQwIvODNozhCJW78Sp30QsY_Xfhabp"
  JWT_AUTH_CONVERTER_PRINICIPAL_ATTRIBUTE: "principal_username"
  MICROSOFT_ENTRA_ID_CLIENT_ID: "b6471db2-0004-46bf-a3e1-143a709e167d"
  MICROSOFT_ENTRA_ID_TENANT_ID: "758c9aae-38da-48e7-9f09-943cae42886b"
  SPRING_AI_OPENAI_API_EMBEDDING_MODEL: "text-embedding-3-small"
  SPRING_AI_OPENAI_OPTIONS_MODEL: "gpt-3.5-turbo"
  SPRING_AI_OPENAI_EMBEDDING_OPTIONS_MODEL: "text-embedding-3-small"
  SPRING_AI_VECTORSTORE_COSMOSDB_ENDPOINT: "https://smym-cosmos.documents.azure.com:443/"
  SPRING_AI_VECTORSTORE_COSMOSDB_INITIALIZE_SCHEMA: "false"
  SPRING_AI_VECTORSTORE_COSMOSDB_DATABASE_NAME: "rag-knowledge-base"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
